name: Static assets check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  static_assets_check:
    name: Static Assets check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ 3.8 ]
        node-version: [ 16 ]
        npm-version: [ 8.5.x ]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install system Packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libxmlsec1-dev
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup npm
      run: npm i -g npm@${{ matrix.npm-version }}

    - name: Install Python dependencies
      run: |
        pip install -r requirements/pip.txt
        pip install -r requirements/edx/development.txt
    - name: Initiate Services
      run: |
        sudo systemctl start mongod
    - name: Run Tests
      env:
        LMS_CFG: lms/envs/bok_choy.yml
        CMS_CFG: cms/envs/bok_choy.yml
      run: |
        echo "$GITHUB_WORKSPACE/node_modules/.bin" >> $GITHUB_PATH
        # npm install
        # npm install -g rtlcss
        # ./scripts/update-assets-dev.sh
        paver update_assets
